pull_request_rules:
  - name: Automated merge for Renovate pull requests
    conditions:
      - author=renovate[bot]
      - status-success=build (14.x)
      - status-success=lint (14.x)
      - status-success=Travis CI - Pull Request
    actions:
      merge:
        method: merge
      label:
        add: ['chore(deps):', '🛠 Improvement']

  - name: Automated dependabot merge
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - status-success=build (14.x)
      - status-success=lint (14.x)
      - status-success=Travis CI - Pull Request
    actions:
      merge:
        method: merge
      label:
        add: ['chore(deps):', '🛠 Improvement']
